### PR TITLE
Fix unhandled exception when no templates have been configured

### LINKED ISSUE #1: Unhandled exception when starting rails app, after adding this gem
I generated a new rails app, added `gem 'consult', '~> 0.5.0'` to the Gemfile, ran `bundle`, then `bundle exec rails s`. This is what happened:

```
$ bundle exec rails s
c:/bin/ruby/243/lib/ruby/gems/2.4.0/gems/consult-0.5.0/lib/consult.rb:70:in `active_templates': private method `select' called for nil:NilClass (NoMethodError)
        from c:/bin/ruby/243/lib/ruby/gems/2.4.0/gems/consult-0.5.0/lib/consult.rb:75:in `render!'
        from c:/bin/ruby/243/lib/ruby/gems/2.4.0/gems/consult-0.5.0/lib/consult/rails/engine.rb:10:in `block in <class:Railtie>'
        from c:/bin/ruby/243/lib/ruby/gems/2.4.0/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
(...snip...)
```

I had not yet added a configuration yaml, so I didn't expect anything to get templated, but I didn't think that it'd stop me from running the app.

### PR DESCRIPTION
**Pull request by aharpervc**
Got this when introducing consult to an app, where I hadn't added the config/consult.yml file yet. The code appears to otherwise support booting up without a config file, except for 1 unhandled exception.

This fixes #1

### CODE REVIEW

File: lib/consult.rb [hunk 1]
```diff
@@ -67,7 +67,7 @@ def env
 
     # Return only the templates that are relevant for the current environment
     def active_templates
-      templates.select(&:should_render?)
+      @templates.select(&:should_render?)
```
Comment (sixfeetover) [inline lib/consult.rb]: Why this change? There's an `attr_reader` on `@templates`.

Comment (aharpervc) [reply lib/consult.rb]: True. I still disagree, but I'll remove this commit from this branch.

**Comment by aharpervc** [comment]
@sixfeetover pr updated with 2 more fixes for unhandled exceptions

File: lib/consult/template.rb [hunk 2]
```diff
@@ -34,7 +34,7 @@ def dest
     end
 
     def should_render?
-      (@config[:environments] == 'all' || @config[:environments].include?(Consult.env)) && expired?
+      (@config[:environments] == 'all' || [@config[:environments]].flatten.include?(Consult.env)) && expired?
```
Comment (sixfeetover) [inline lib/consult/template.rb:37]: This one is interesting. `@config[:environments]` should already be an array if we format our YAML properly, which I don't think we currently are. In other words:

```yml
environments: ['production', 'staging']
```

or

```yml
environments:
  - production
  - staging
```

Should both work. We should modify consult to assume standard YAML conventions here.

Comment (aharpervc) [reply lib/consult/template.rb:37]: I don't have a problem with supporting both `environments: <string>` and `environments: <array>`. It's more ergonomic for single environments and this is a safe, low energy change.

However, I still think that `consult.yml` _should_ be refactored with environment specific blocks, rails style. I think we can figure out how to do the right thing with that in non rails situations, and then this particular question becomes moot.

Comment (aharpervc) [reply lib/consult/template.rb:37]: This is moot with https://github.com/veracross/consult/pull/11
